### PR TITLE
Cross compile on arm64

### PR DESCRIPTION
**Pull request by saraedum**

### CODE REVIEW

**Comment by saraedum** [comment]
As terrifying as it sounds, it seems we need to find a way to cross compile here.

**Comment by saraedum** [comment]
@conda-forge-admin, please rerender.

**Comment by saraedum** [comment]
Hey @isuruf, hope I don't break your run now. I don't understand why the `-dynamiclib` flag is not being picked up…

**Comment by isuruf** [comment]
> I don't understand why the -dynamiclib flag is not being picked up…


It's not?

**Comment by saraedum** [comment]
No, it's missing in the arm64 build from the ld call.

**Comment by isuruf** [comment]
Can you show me the exact line in the log you are looking at?

**Comment by saraedum** [comment]
Wow, you fixed it :)

**Comment by saraedum** [comment]
So, I'll remove some of the verbosity and then this is good to go?

**Pull request merged**
